
image: gcc:latest

pipelines:
  default:
    - parallel:

      - step:
          name: Build Debug
          script:
            - apt update && apt -y install libgtest-dev libpugixml-dev cmake
            - cmake -E make_directory build_Debug

            - cd build_Debug
            - cmake .. -DCMAKE_BUILD_TYPE=Debug
            - cmake --build . --config Debug --parallel $(nproc)

            - if [ -f $PWD/ant4c ]; then $PWD/ant4c; fi
            - if [ -f $PWD/ant4c_tests ]; then $PWD/ant4c_tests --tests_xml=../tests.xml --tests_exec_app=$PWD/tests_exec_app --tests_base_directory=..; fi
            - if [ ! -f $PWD/ant4c_tests ]; then echo "File '"$PWD/ant4c_tests"' not exists. Tests will not run." ; ls -lah ; fi

          artifacts:
            - build_Debug/*

      - step:
          name: Build Release
          script:
            - apt update && apt -y install libgtest-dev libpugixml-dev cmake
            - cmake -E make_directory build_Release

            - cd build_Release
            - cmake .. -DCMAKE_BUILD_TYPE=Release
            - cmake --build . --config Release --parallel $(nproc)

            - if [ -f $PWD/ant4c ]; then $PWD/ant4c; fi
            - if [ -f $PWD/ant4c_tests ]; then $PWD/ant4c_tests --tests_xml=../tests.xml --tests_exec_app=$PWD/tests_exec_app --tests_base_directory=..; fi
            - if [ ! -f $PWD/ant4c_tests ]; then echo "File '"$PWD/ant4c_tests"' not exists. Tests will not run." ; ls -lah ; fi

          artifacts:
            - build_Release/*
