name: CMake

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ github.ref_name }}
      ${{ matrix.os }}
      ${{ matrix.compiler }}
      ${{ matrix.optimized && 'release' || 'debug' }}

      # ${{ matrix.patch && 'First patch apply' || 'no first patch' }}
      # ${{ matrix.patch_2 && 'Second patch apply' || 'no second patch' }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [mingw]
        os: [windows-2022]
        optimized: [false]
        target_platform: [x64]
        # patch: [true, false]
        # patch_2: [true, false]
        # exclude:
        # - os: windows-2019
        #   patch: true

        # - os: windows-2019
        #   patch_2: true

        # - patch: true
        #   patch_2: true

    env:
      CMAKE_BUILD_DIR: >-
        ${{ format(
            startsWith(matrix.os, 'windows') && '{0}\build' || '{0}/build',
            github.workspace) }}
      CMAKE_GENERATOR: ${{ 'mingw' == matrix.compiler && '-G "MinGW Makefiles"' || '' }}
      CMAKE_BUILD_TYPE: >-
        ${{ format(
            'msvc' == matrix.compiler && '' || '-DCMAKE_BUILD_TYPE={0}',
            (matrix.optimized && 'Release' || 'Debug')) }}
      CMAKE_CONFIG_TYPE: ${{ matrix.optimized && 'Release' || 'Debug' }}
      CMAKE_TARGET_PLATFORM: >-
        ${{ format(
            'msvc' == matrix.compiler && '-A {0}' || '',
            matrix.target_platform) }}
      EXECUTABLE_EXTENSION: ${{ startsWith(matrix.os, 'windows') && '.exe' || '' }}
      BINARY_PATH: >-
        ${{ format(
              ('msvc' == matrix.compiler && '{0}\build\{1}\') ||
              (startsWith(matrix.os, 'windows') && '{0}\build\' || '{0}/build/'),
            github.workspace,
            matrix.optimized && 'Release' || 'Debug') }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Adding path to a bin directory of MinGW
      if: ${{ 'mingw' == matrix.compiler }}
      run: echo "C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin;" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create project files
      run: >-
        cmake
        ${{ env.CMAKE_TARGET_PLATFORM }}
        ${{ env.CMAKE_GENERATOR }}
        ${{ env.CMAKE_BUILD_TYPE }}
        -S ${{ github.workspace }}
        -B ${{ env.CMAKE_BUILD_DIR }}

    - name: Build
      run: >-
        cmake
        --build ${{ env.CMAKE_BUILD_DIR }}
        --config ${{ env.CMAKE_CONFIG_TYPE }}

    - name: Run main application
      if: ${{ 'mingw' == matrix.compiler }}
      shell: pwsh
      run: |
        $paths = $Env:PATH.Split(';')
        $paths_ = ""
        ForEach($path in $paths)
        {
          $path_ = $path.ToLower()
          If (($path_ -clike "c:\strawberry*") -or
          	  ($path_ -clike "c:\program files\git\mingw64*") -or
          	  ($path_ -clike "c:\programdata*"))
          {
          }
          Else
          {
            $paths_ += $path + ";"
          }
        }
        $Env:PATH = $paths_
        Write-Host $Env:PATH
        $app = "${{ env.BINARY_PATH }}main${{ env.EXECUTABLE_EXTENSION }}"
        $process = Start-Process -FilePath "$app" -NoNewWindow -Wait -PassThru
        if ($process.ExitCode -ne 0)
        {
          $app = "Exit code of application '$app' is not equal to the '0', instead it - '{0}'." -f $process.ExitCode
          throw (New-Object -TypeName System.Exception -ArgumentList $app)
        }
        Write-Host "The application '$app' is success started."
