name: modules_net_CMake

on:
  push:
    branches:
    - CI

  pull_request:
    branches:
    - CI

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Fetch prebuild of third-party libraries
      run: git fetch origin ${{ matrix.os }}

    - name: Checkout third-party libraries
      run: git checkout origin/${{ matrix.os }} -- .

    - name: Fetch develop
      run: git fetch origin develop

    - name: Checkout develop
      run: git checkout origin/develop -- .

    - name: Create Build Environment (Unix like)
      if: ${{ 'Windows' != runner.os }}
      run: cmake -E make_directory ${{ github.workspace }}/build-modules-net

    - name: Create project files (Unix like)
      if: ${{ 'Windows' != runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE="Release" -DGTEST_BINARY_PATH=${{ github.workspace }}/${{ matrix.os }} -DPUGIXML_BINARY_PATH=${{ github.workspace }}/${{ matrix.os }} -DNET_MODULE_TESTS=""

    - name: Build project files (Unix like)
      if: ${{ 'Windows' != runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: cmake --build ${{ github.workspace }}/build-modules-net --config Release --target net.module_tests

    - name: Run Tests (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run 'hostfxr_resolve_sdk' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export hostfxr_resolve_sdk=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run 'hostfxr_get_available_sdks' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export hostfxr_get_available_sdks=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run 'hostfxr_get_native_search_directories' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export hostfxr_get_native_search_directories=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run 'hostfxr_resolve_sdk2' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export hostfxr_resolve_sdk2=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run 'test_hostfxr_initialize_for_dotnet_command_line' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_initialize_for_dotnet_command_line=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_initialize_for_runtime_config' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_initialize_for_runtime_config=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_run_app' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_run_app=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_get_runtime_properties' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_get_runtime_properties=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_get_runtime_property_value' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_get_runtime_property_value=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_set_runtime_property_value' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_set_runtime_property_value=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_get_runtime_delegate' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_get_runtime_delegate=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*


    - name: Run Test 'test_hostfxr_set_error_writer' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_set_error_writer=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_hostfxr_main_bundle_startupinfo' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_hostfxr_main_bundle_startupinfo=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Run Test 'test_file_is_assembly' (macOS)
      if: ${{ 'macOS' == runner.os }}
      working-directory: ${{ github.workspace }}/build-modules-net
      run: |
        export test_hostfxr_=""
        export test_file_is_assembly=""
        ${{ github.workspace }}/build-modules-net/net.module_tests --tests_xml=${{ github.workspace }}/tests.xml --build_file=${{ github.workspace }}/modules/net/net.xml -D:net_host_folder="$DOTNET_ROOT/packs/Microsoft.NETCore.App.Host.osx-x64" -D:sub_folder="runtimes/osx-x64/native" -D:nethost_file_name="libnethost.dylib" -D:fxr_folder="$DOTNET_ROOT/host/fxr" --gtest_filter=TestNetModuleEx*

    - name: Upload binaries
      if: ${{ 'Windows' != runner.os }}
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{ matrix.os }}
        path: |
          ${{ github.workspace }}/build-modules-net
          ${{ github.workspace }}/modules/net/bin
        retention-days: 1
